# Generated by Django 4.0.2 on 2022-02-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('device_number', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('measure_type', models.IntegerField()),
                ('glucose_level', models.IntegerField()),
            ],
        ),
    ]
